name: Release internal tools

on:
  push:
    branches:    
      - main
  schedule:
    - cron: '0 22 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Install dependencies
        run: go mod download && go mod verify

      - name: Build
        run: ./build_internal_tools.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Internal tools"
          prerelease: false
          files: |
            .bin/*
